##################################################################################################
# database-pgadmin
##################################################################################################
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: database-pgadmin
spec:
  hosts:
    - database-pgadmin.dev.localhost
  gateways:
    - services-gateway
  http:
  - route:
    - destination:
        host:
          database-pgadmin.tools.svc.cluster.local
        port:
          number: 80