##################################################################################################
# iam-provider
##################################################################################################
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: iam-provider
spec:
  hosts:
    - iam-provider.aimerzarashi.com
  gateways:
    - services
  http:
  - route:
    - destination:
        host:
          iam-provider.services.svc.cluster.local
        port:
          number: 8080