apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: require-keycloak-jwt
spec:
  selector:
    matchLabels:
      app: command-api
  jwtRules:
  - issuer: https://iam-provider.aimerzarashi.com/realms/aimerzarashi
#    jwksUri: http://iam-provider:8080/realms/aimerzarashi/protocol/openid-connect/certs
    jwks: |
      {"keys":[{"kid":"382mqSzRMr2BIvIJW0ANQxQue9Pb5AP6El7cRns4Xuw","kty":"RSA","alg":"RSA-OAEP","use":"enc","n":"oGoJiBHTip6NOcfEWZSPJB-AtBchxm67phFg7XVlguUPlCoJPp-a3Uo2xNxjAA0i42MgeB94iyZOCgYLdQka02VETKtLyZ6OgNuIuXWtLeehR3Pa7T7tNCPceNimUgWTkiWPIjnpA0duo8PGcDX7f0S4Uurqztz4yVhdJvmG8BRRDiMR_2fneNyskxvJieI8ZmvW2ScEbia7FvARGmLtDMRpoRox8KQbOPC7HNGan7nxfEejQl0WxgWhlIOMY3CEgRkevhszDgZIDsEColH0U5Js8e5O8OHjCkS6-i7K94MPOycvWlwWGtW5NC5rwF03qWgkbxG9CtmdGhwDJhVGZQ","e":"AQAB","x5c":["MIICpzCCAY8CBgGK4+bLhDANBgkqhkiG9w0BAQsFADAXMRUwEwYDVQQDDAxhaW1lcnphcmFzaGkwHhcNMjMwOTMwMDIyMjQ4WhcNMzMwOTMwMDIyNDI4WjAXMRUwEwYDVQQDDAxhaW1lcnphcmFzaGkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCgagmIEdOKno05x8RZlI8kH4C0FyHGbrumEWDtdWWC5Q+UKgk+n5rdSjbE3GMADSLjYyB4H3iLJk4KBgt1CRrTZURMq0vJno6A24i5da0t56FHc9rtPu00I9x42KZSBZOSJY8iOekDR26jw8ZwNft/RLhS6urO3PjJWF0m+YbwFFEOIxH/Z+d43KyTG8mJ4jxma9bZJwRuJrsW8BEaYu0MxGmhGjHwpBs48Lsc0ZqfufF8R6NCXRbGBaGUg4xjcISBGR6+GzMOBkgOwQKiUfRTkmzx7k7w4eMKRLr6Lsr3gw87Jy9aXBYa1bk0LmvAXTepaCRvEb0K2Z0aHAMmFUZlAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAEsdjbaUfXdKwLzbvWer8ILrpgBQHJwZVVLV25ollsHcVE+q7Lr49DgOy1f+8Ie0OKM27VQNcz9OPzBXZtkG1CHFK9hk08CLg1r9tXxC/4BmJu4k3cbSGFf4jc9EHV6KEOV6dZ362TDC3t+t5EdchAIj5tunAB9P18tk2+FC+V8KcBM4TGXKdoKRtWpTq9B9djKzmPIdncJztKWb0yv58CsKWWmFYPEeCtgI+u/aUIKVHejhJbGFxTYqBKNcTS+Xdht56AZunAOIX+2Q9VHPvYYSpr2l0IEpdfNsCekCFR3J9BOnwRgQtrv4NPWM1/5g8udmvTjyQ4ZnOLAKb9/VmNA="],"x5t":"IEck8NXZADuSx9Bz8bVQ3OC51hU","x5t#S256":"khiViBOlNFkmiFzR0v6oFKC3C0WxxWWzjLD40MlAERM"},{"kid":"TGyDQxshhrBFRIXkmRv1XY_9KrJE9X41zGqfZ7E5bnA","kty":"RSA","alg":"RS256","use":"sig","n":"p02dbGDzhCTfYSBzbEonC1PwU9zu7jF0OKsbJkwNdBNT137ULZwbK20wAefuPJ-inpofL-wVFpcP5VnCXKBghkmBu_uX1Zkg78CJGxGoFrVTv1X2ucV-AdD12HDO3D8ef82_aFpK1ZOE3S9XMQh8pKDM3TI7QUK1qJt4tgJjqWbQjKuWfD1dzIqUzDOyXKQPqfhsPlpNCCpXlQCtEIoHSZ-fwuDGEpxvqpZjnx_uvGDy3xg7QmuxdmXzK8jfbPAyiD499mQMSEZSlLQSiHnapMzqcrhj0ww_iKhet1dKKSn-o7RTj_UP1eFKgpbBOP5-X-FUDlBm5tDMGxYZSCa2Jw","e":"AQAB","x5c":["MIICpzCCAY8CBgGK4+bKWTANBgkqhkiG9w0BAQsFADAXMRUwEwYDVQQDDAxhaW1lcnphcmFzaGkwHhcNMjMwOTMwMDIyMjQ3WhcNMzMwOTMwMDIyNDI3WjAXMRUwEwYDVQQDDAxhaW1lcnphcmFzaGkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCnTZ1sYPOEJN9hIHNsSicLU/BT3O7uMXQ4qxsmTA10E1PXftQtnBsrbTAB5+48n6Kemh8v7BUWlw/lWcJcoGCGSYG7+5fVmSDvwIkbEagWtVO/Vfa5xX4B0PXYcM7cPx5/zb9oWkrVk4TdL1cxCHykoMzdMjtBQrWom3i2AmOpZtCMq5Z8PV3MipTMM7JcpA+p+Gw+Wk0IKleVAK0QigdJn5/C4MYSnG+qlmOfH+68YPLfGDtCa7F2ZfMryN9s8DKIPj32ZAxIRlKUtBKIedqkzOpyuGPTDD+IqF63V0opKf6jtFOP9Q/V4UqClsE4/n5f4VQOUGbm0MwbFhlIJrYnAgMBAAEwDQYJKoZIhvcNAQELBQADggEBADEGgYAPc4dYyCrM3KuYaKg95TIYsf0q2TtajSXBGzoNMVVUf0X8myKVuY4dzIhV3Lk/6Gk8eh8gjzmR4LHmUeSrfe2b71kv9qsVncqWCbqfyvO0+WVS5jrrN+wBkVWXt5FSm3ktBbrb8TUHkYIR+ZsSmJR65bEiD4P42OYuCcSaTtvF5OJWelboZ6YyBunOCtJo2eJkKxBZK4rA2VrVAGu9RCNoiLkMxpk11P2iXRVrNnxJHvBN4UyG+DgRDggRyFleDm05ihFJLI93N+RhA6hwzrHqtxcV8kFxvUGw39orm76zlm1m1Q4/5nfMVguAhakxBQfj/QPKRpmptqbCj/E="],"x5t":"VpxGSdxS39WJTQpBEWk6x0ystOo","x5t#S256":"YGrmraXHHdQxbaPlZtnEpk61sVyLnCDir_dY3YlBnNM"}]}
    fromHeaders:
    - name: Authorization
      prefix: 'Bearer '
    forwardOriginalToken: true
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: command-api
spec:
  selector:
    matchLabels:
      app: command-api
  action: ALLOW
  rules:
  - when:
    - key: request.auth.claims[iss]
      values: ["https://iam-provider.aimerzarashi.com/realms/aimerzarashi"]