openapi: 3.0.0
info:
  version: 1.0.0
  title: Authorization API
  description: A OpenAPI to illustrate Authorization API concepts

servers:
  - url: https://authz-api.aimerzarashi.com

paths:
  /authorization:
    get:
      description: Authorization endpoint
      operationId: ReqestToken
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: private_key_jwt
      responses:
        "302":
          description: Found
  /callback:
    get:
      description: callback endpoint
      security:
        - bearerAuth: []
      responses:
        "302":
          description: Found
  /decision:
    get:
      description: Authorization decision endpoint
      security:
        - bearerAuth: []
      responses:
        "302":
          description: Found
  /token:
    post:
      description: Token endpoint
      operationId: ReqestToken
      responses:
        "200":
          description: Ok
        '401':
          $ref: '#/components/responses/UnauthorizedError'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
security:
  - bearerAuth: []
