openapi: 3.0.0
info:
  version: 1.0.0
  title: Command API
  description: A OpenAPI to illustrate Command API concepts

servers:
  - url: https://command-api.aimerzarashi.com

paths:
  /stock/items:
    post:
      description: Create a new sales item
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SaleItem"
      responses:
        "201":
          description: 作成されました
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SaleItem"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SaleItem:
      type: object
      properties:
        id:
          type: string
          format: cuid
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - createdAt
security:
  - bearerAuth: []
