##################################################################################################
# database-pgadmin
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: database-pgadmin
  labels:
    app: database-pgadmin
    service: database
spec:
  ports:
    - port: 80
      name: tcp
      appProtocol: http
  selector:
    app: database-pgadmin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-pgadmin
  labels:
    account: database-pgadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-pgadmin
  labels:
    app: database-pgadmin
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-pgadmin
      version: v1
  template:
    metadata:
      labels:
        app: database-pgadmin
        version: v1
    spec:
      serviceAccountName: database-pgadmin
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: database-pgadmin
          image: dpage/pgadmin4
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi
          tty: true
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: database-pgadmin
          volumeMounts:
            - name: database-pgadmin
              mountPath: /var/lib/pgadmin
      volumes:
        - name: database-pgadmin
          persistentVolumeClaim:
            claimName: database-pgadmin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pgadmin
  labels:
    app: database-pgadmin
spec:
  storageClassName: database-pgadmin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
