##################################################################################################
# shop-command
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: shop-command
  labels:
    app: shop-command
    service: shop
spec:
  ports:
    - port: 3000
      name: tcp
      appProtocol: http
  selector:
    app: shop-command
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shop-command
  labels:
    account: shop-command
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-command
  labels:
    app: shop-command
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-command
      version: v1
  template:
    metadata:
      labels:
        app: shop-command
        version: v1
    spec:
      serviceAccountName: shop-command
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: shop-command
          image: node:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi
          tty: true
          ports:
            - containerPort: 3000
          workingDir: /my-app
          command:
            - "sh"
            - "-c"
            - |
              npm install;
              (npm run prisma migrate dev; echo);
              npm run dev;
          volumeMounts:
            - name: shop-command-app
              mountPath: /my-app
      initContainers:
        - name: init-env
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              echo "" > .env.work
          volumeMounts:
            - name: shop-command-app
              mountPath: /my-app
        - name: init-env-db
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          workingDir: /my-app
          command:
            - sh
            - -c
            - |
              echo 'DATABASE_URL="postgres://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"' >> .env.work
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-resource
                  key: POSTGRESQL_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-resource
                  key: POSTGRESQL_PASSWORD
          envFrom:
            - configMapRef:
                name: shop-command
          volumeMounts:
            - name: shop-command-app
              mountPath: /my-app
        - name: wait-db
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              while ! nc -z database-event 5432; do
                echo "Waiting..."
                sleep 5
              done
        - name: finish
          image: curlimages/curl:latest
          imagePullPolicy: IfNotPresent
          workingDir: /my-app
          command:
            - sh
            - -c
            - |
              mv .env.work .env.local
          volumeMounts:
            - name: shop-command-app
              mountPath: /my-app
      volumes:
        - name: shop-command-app
          persistentVolumeClaim:
            claimName: shop-command-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-command
data:
  DB_HOST: "database-event"
  DB_PORT: "5432"
  DB_NAME: "shop"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shop-command-app
  labels:
    app: shop-command
spec:
  storageClassName: shop-command-app
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
