##################################################################################################
# shop-command
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: shop-command
  labels:
    app: shop-command
    service: shop
spec:
  ports:
    - port: 3000
      name: tcp
      appProtocol: http
  selector:
    app: shop-command
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shop-command
  labels:
    account: shop-command
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-command
  labels:
    app: shop-command
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-command
      version: v1
  template:
    metadata:
      labels:
        app: shop-command
        version: v1
    spec:
      serviceAccountName: shop-command
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: shop-command
          image: node:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 500m
              memory: 500Mi
          tty: true
          ports:
            - containerPort: 3000
          workingDir: /my-app
          command:
            - "sh"
            - "-c"
            - |
              npm install;
              (npm run prisma migrate dev; echo);
              npm run dev;
          volumeMounts:
            - name: shop-command-app
              mountPath: /my-app
      volumes:
        - name: shop-command-app
          persistentVolumeClaim:
            claimName: shop-command-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shop-command-app
  labels:
    app: shop-command
spec:
  storageClassName: shop-command-app
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
