##################################################################################################
# shop-query
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: shop-query
  labels:
    app: shop-query
    service: shop
spec:
  ports:
    - port: 5000
      name: tcp
      appProtocol: http
  selector:
    app: shop-query
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shop-query
  labels:
    account: shop-query
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-query
  labels:
    app: shop-query
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-query
      version: v1
  template:
    metadata:
      labels:
        app: shop-query
        version: v1
    spec:
      serviceAccountName: shop-query
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: shop-query
          #          image: graphile/postgraphile:latest
          image: my_postgraphile
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi
          tty: true
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: database-resource
          args:
            [
              "--subscriptions",
              "--watch",
              "--dynamic-json",
              "--no-setof-functions-contain-nulls",
              "--no-ignore-rbac",
              "--show-error-stack=json",
              "--extended-errors",
              "hint,detail,errcode",
              "--append-plugins",
              "@graphile-contrib/pg-simplify-inflector",
              "--export-schema-graphql",
              "schema.graphql",
              "--enhance-graphiql",
              "--allow-explain",
              "--enable-query-batching",
              "--legacy-relations",
              "omit",
              "--connection",
              "postgres://$(POSTGRESQL_USERNAME):$(POSTGRESQL_PASSWORD)@database-resource:5432/shop",
              "--owner-connection",
              "postgres://postgres:$(POSTGRESQL_POSTGRES_PASSWORD)@database-resource:5432/shop",
              "--schema",
              "public",
            ]
      initContainers:
        - name: wait-db
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              while ! nc -z database-resource 5432; do
                echo "Waiting..."
                sleep 5
              done
