##################################################################################################
# authorization
##################################################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: authorization
type: Opaque
data:
# openssl rand -base64 32
# echo -n "XXX" | openssl enc -e -base64
  AUTHZ_SECRET_KEY: YTgrS2ZxMmZwUGl5VERYaXF4SFhRZWtYdk9xNCtLdzVVSDI4aE9pMWJyaz0= #a8+Kfq2fpPiyTDXiqxHXQekXvOq4+Kw5UH28hOi1brk=
  AUTHZ_PUBLIC_KEY: I2FuQy8xSzNUWk9Nb3VwaCtqd0Z3VnpWYTJGUUY3NHB0MDc1eVRNQ3haTzA9 #anC/1K3TZOMouph+jwFwVzVa2FQF74pt075yTMCxZO0=
