##################################################################################################
# database-ui
##################################################################################################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin
  labels:
    type: local
spec:
  storageClassName: pgadmin
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/myprojects/ts-cqrs-es-v1/tools/database/pgadmin"