/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/stock/items": {
    /** Register stock items */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["StockItem"];
        };
      };
      responses: {
        /** @description Successful Created */
        201: {
          content: never;
        };
        /** @description Bad request */
        400: {
          content: never;
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
        /** @description Internal Server Error */
        500: {
          content: never;
        };
      };
    };
  };
  "/inbound/plans": {
    /** Register for inbound plans */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["InboundPlan"];
        };
      };
      responses: {
        /** @description Successful Created */
        201: {
          content: never;
        };
        /** @description Bad request */
        400: {
          content: never;
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
        /** @description Internal Server Error */
        500: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    InboundPlan: {
      /** Format: date */
      arrivalDate: string;
      itemId: string;
      quantity: number;
      unit: string;
    };
    StockItem: {
      name: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
