##################################################################################################
# command-api
##################################################################################################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: command-api-app
  labels:
    type: local
spec:
  storageClassName: command-api-app
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/myprojects/ts-cqrs-es-v1/command/api"