##################################################################################################
# command-api
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: command-api
  labels:
    app: command-api
    service: command
spec:
  ports:
  - port: 3000
    name: tcp
    appProtocol: http
  selector:
    app: command-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: command-api
  labels:
    account: command-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-api
  labels:
    app: command-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command-api
      version: v1
  template:
    metadata:
      labels:
        app: command-api
        version: v1
    spec:
      serviceAccountName: command-api
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: command-api
          image: node:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 500m
              memory: 500Mi
          tty: true
          ports:
            - containerPort: 3000
          workingDir: /my-app
          command: ["/bin/sh"]
          args: ["-c", "npm install; npm run dev"]
          volumeMounts:
          - name: command-api-app
            mountPath: /my-app
      volumes:
      - name: command-api-app
        persistentVolumeClaim:
          claimName: command-api-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: command-api-app
  labels:
    app: command-api
spec:
  storageClassName: command-api-app
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi