##################################################################################################
# database-resource
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: database-resource
  labels:
    app: database-resource
    service: database
spec:
  ports:
  - port: 5432
    name: tcp
  selector:
    app: database-resource
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-resource
  labels:
    account: database-resource
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-resource
  labels:
    app: database-resource
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-resource
      version: v1
  template:
    metadata:
      labels:
        app: database-resource
        version: v1
    spec:
      serviceAccountName: database-resource
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: database-resource
          image: bitnami/postgresql:latest
          imagePullPolicy: IfNotPresent 
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 500m
              memory: 500Mi
          tty: true
          ports:
            - containerPort: 5432
          envFrom:
          - secretRef:
              name: database-resource
          volumeMounts:
          - name: database-resource-data
            mountPath: /bitnami/postgresql/data
          - name: database-resource-conf
            mountPath: /bitnami/postgresql/conf
      volumes:
      - name: database-resource-data
        persistentVolumeClaim:
          claimName: database-resource-data
      - name: database-resource-conf
        persistentVolumeClaim:
          claimName: database-resource-conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-resource-data
  labels:
    app: database-resource
spec:
  storageClassName: database-resource-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-resource-conf
  labels:
    app: database-resource
spec:
  storageClassName: database-resource-conf
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi